services:

  backend:
    build:
      context: ./backend
    container_name: worklink-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: worklink-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
